In [1]:
from loaders import Loaders
from utils import Utils
ld= Loaders()
utils= Utils()

In [2]:

from loaders import Loaders
ld = Loaders()
path_archivo = r"input/base_sae.xlsx"  # <-- cambia si tu ruta es distinta
nombre_hoja = "EXPEDIENTES"                       # <-- tu hoja se llama "query"
df = ld.cargar_excel(path_archivo, nombre_hoja)

if df is None:
    raise FileNotFoundError(
        "No se pudo cargar el Excel. Revisa:\n"
        f"- Ruta: {path_archivo}\n"
        f"- Hoja: {nombre_hoja}\n"
        "Si el archivo expiró en el chat, vuelve a subirlo o cópialo a ./input/"
    )


print("✅ Base cargada correctamente")
print("Shape (filas, columnas):", df.shape)
print("\nColumnas:")
print(df.columns.tolist())

display(df.head(10))
display(df.info())

# Nulos por columna (top 30 para no saturar)
nulos = df.isna().sum().sort_values(ascending=False)
display(nulos.head(30))

✅ Base cargada correctamente
Shape (filas, columnas): (120587, 11)

Columnas:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,DATOS GENERALES,NaN,NaN,ETAPA Y ACTIVIDAD ACTUAL,NaN,NaN,NaN,NaN
2,EXPEDIENTE,TIPO TRÁMITE,TRÁMITE,ESTADO ACTUAL,REGIONAL,FECHA APERTURA,ETAPA,ACTIVIDAD,RESPONSABLE,OFICINA RESPONSABLE,ES MINERO
3,1,Permisivo,Concesión de Aguas Superficiales,Seguimiento y Control,Sabana Centro,1945-02-01 00:00:00,Seguimiento y Control,Acto Administrativo,FORERO FORERO DANIELA,Sabana Centro,NO
4,2,Permisivo,Concesión de Aguas Superficiales,Archivado,Ubate,1948-03-15 00:00:00,Archivado,Archivado,No Aplica,Ubate,NO
5,3,Permisivo,Plan de Manejo Ambiental,Archivado,Sabana Centro,1951-11-22 00:00:00,Archivado,Archivado,No Aplica,Sabana Centro,NO
6,4,Permisivo,Concesión de Aguas Superficiales,Archivado,Ubate,1954-11-25 00:00:00,Archivado,Archivado,No Aplica,Ubate,NO
7,5,Permisivo,Permiso de Extracción Material de Arrastre,Archivado,Bajo Magdalena,1955-09-23 00:00:00,Archivado,Archivado,No Aplica,Bajo Magdalena,NO
8,6,Permisivo,Plan de Manejo Ambiental,Archivado,Ubate,1955-11-27 00:00:00,Archivado,Archivado,No Aplica,Ubate,NO
9,7,Permisivo,Concesión de Aguas Superficiales,Archivado,Alto Magdalena,1957-07-12 00:00:00,Archivado,Archivado,No Aplica,Alto Magdalena,NO

<class 'pandas.DataFrame'>
RangeIndex: 120587 entries, 0 to 120586
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   120585 non-null  object
 1   Unnamed: 1   120585 non-null  str
 2   Unnamed: 2   120585 non-null  str
 3   Unnamed: 3   120586 non-null  str
 4   Unnamed: 4   120585 non-null  str
 5   Unnamed: 5   120585 non-null  object
 6   Unnamed: 6   120075 non-null  str
 7   Unnamed: 7   120074 non-null  str
 8   Unnamed: 8   83296 non-null   str
 9   Unnamed: 9   83296 non-null   str
 10  Unnamed: 10  120585 non-null  str
dtypes: object(2), str(9)
memory usage: 10.1+ MB

None

Unnamed: 9     37291
Unnamed: 8     37291
Unnamed: 7       513
Unnamed: 6       512
Unnamed: 2         2
Unnamed: 0         2
Unnamed: 1         2
Unnamed: 4         2
Unnamed: 5         2
Unnamed: 10        2
Unnamed: 3         1
dtype: int64

In [3]:

path_reparto = r"input/base_reparto.xlsx"   # ajusta si cambia la ruta
nombre_hoja_reparto = 0  # usa 0 si no sabes el nombre exacto de la hoja

df_reparto = ld.cargar_excel(path_reparto, nombre_hoja_reparto)

if df_reparto is None:
    raise FileNotFoundError(
        "No se pudo cargar base_reparto.xlsx. Revisa:\n"
        f"- Ruta: {path_reparto}\n"
        f"- Hoja: {nombre_hoja_reparto}"
    )

print("✅ Base REPARTO cargada correctamente")
print("Shape (filas, columnas):", df_reparto.shape)
print("\nColumnas:")
print(df_reparto.columns.tolist())

display(df_reparto.head(10))
display(df_reparto.info())

# Nulos por columna (top 30)
nulos_reparto = df_reparto.isna().sum().sort_values(ascending=False)
display(nulos_reparto.head(30))

✅ Base REPARTO cargada correctamente
Shape (filas, columnas): (358, 12)

Columnas:
['ESTADO', 'NOMBRE CONTRATISTA', 'DOCUMENTO IDENTIFICACIÓN', 'LUGAR DE EJECUCIÓN', 'GRUPO', 'SUBGRUPO', 'CTO B', 'NÚMERO DE CONTRATO', 'FECHA DE INICIO', 'FECHA DE TERMINACIÓN', 'SUPERVISOR', 'HOJA']

,ESTADO,NOMBRE CONTRATISTA,DOCUMENTO IDENTIFICACIÓN,LUGAR DE EJECUCIÓN,GRUPO,SUBGRUPO,CTO B,NÚMERO DE CONTRATO,FECHA DE INICIO,FECHA DE TERMINACIÓN,SUPERVISOR,HOJA
0,EN EJECUCIÓN,MONICA ALEJANDRA CAMARGO SILVA,1000326898,BOGOTÁ LA CALERA,JUDICANTES,JUDICANTES,NaN,20,2026-01-14 00:00:00,2026-11-13,YUBER YESID CARDENAS PULIDO Director Regional,CTOS NUEVOS 2026
1,CONTRATO PUBLICADO,ANA MARIA GARCIA RODRIGUEZ,1072752326,BAJO MAGDALENA,12.2.4 SAE,APOYO SAE,NaN,976,2026-01-20 00:00:00,2026-06-30,JUAN FILIVERTO COTRINO GUEVARA DIRECTOR ...,CTOS NUEVOS 2026
2,EN EJECUCIÓN,LUCERO DÍAZ ARROYO,1104768,SUBDIRECCIÓN,NaN,NaN,NaN,1132,2026-01-29 00:00:00,2026-06-30,BRAYAN GUILLERMO MARTINEZ Subdirector General...,CTOS NUEVOS 2026
3,EN EJECUCIÓN,ANGELA ALEJANDRA NIÑO PINZÓN,1019069831,SABANA CENTRO,12.2.3 RESUELTO,NOTIFICADOR,NaN,982,2026-01-29 00:00:00,2026-06-30,ANDRES MAURICIO GARZON ORJUELA DIRECTOR REGI...,CTOS NUEVOS 2026
4,CONTRATO PUBLICADO,ANGELA MARIA BEDOYA GONZALEZ,41950886,DIRECCIÓN JURÍDICA,12.2.1 EN TRÁMITE,SUSTACIADOR - REVISOR,NaN,768,2026-01-29 00:00:00,2026-06-30,JHOANNA ALEXANDRA MONTOYA MUÑOZ ...,CTOS NUEVOS 2026
5,EN EJECUCIÓN,ANGIE NATALIA OVALLE ROMERO,1072431911,TEQUENDAMA,12.2.3 RESUELTO,NOTIFICADOR,NaN,1134,2026-01-29 00:00:00,2026-06-30,NYDIA CRUZ ORTEGA DIRECTORA REGIONAL,CTOS NUEVOS 2026
6,EN EJECUCIÓN,CAMILO ANDRES BURNEO SANCHEZ,1000611567,DIRECCIÓN JURÍDICA,12.2.6 UIGA,APOYO ADMINISTRATIVO UIGA,NaN,1081,2026-01-29 00:00:00,2026-06-30,JOAQUIN FERNANDO SARMIENTO CARDENAS ...,CTOS NUEVOS 2026
7,EN EJECUCIÓN,ANDY ESTEBAN PEÑA HUERTAS,1049641178,BOGOTÁ LA CALERA,12.2.1 EN TRÁMITE,RELLENO DOÑA JUANA,NaN,302,2026-01-20 00:00:00,2026-06-30,YUBER YESID CARDENAS PULIDO DIRECTOR REGIO...,CTOS NUEVOS 2026
8,EN EJECUCIÓN,CRISTIAN JOAQUIN GIL APONTE,1049604549,DIRECCIÓN JURÍDICA,12.2.3 RESUELTO,NOTIFICADOR,NaN,481,2026-01-21 00:00:00,2026-06-30,NELLY AVELLA SANABRIA ...,CTOS NUEVOS 2026
9,EN EJECUCIÓN,DAISY YOLIMA CASAS RICO,53010120,DIRECCIÓN JURÍDICA,12.2.6 UIGA,ABOGADOS UIGA,NaN,325,2026-01-19 00:00:00,2026-06-30,JOAQUIN FERNANDO SARMIENTO CARDENAS ...,CTOS NUEVOS 2026

<class 'pandas.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ESTADO                    358 non-null    str
 1   NOMBRE CONTRATISTA        358 non-null    str
 2   DOCUMENTO IDENTIFICACIÓN  305 non-null    object
 3   LUGAR DE EJECUCIÓN        358 non-null    str
 4   GRUPO                     354 non-null    str
 5   SUBGRUPO                  348 non-null    str
 6   CTO B                     18 non-null     str
 7   NÚMERO DE CONTRATO        358 non-null    int64
 8   FECHA DE INICIO           307 non-null    object
 9   FECHA DE TERMINACIÓN      349 non-null    datetime64[us]
 10  SUPERVISOR                186 non-null    str
 11  HOJA                      358 non-null    str
dtypes: datetime64[us](1), int64(1), object(2), str(8)
memory usage: 33.7+ KB

None

CTO B                       340
SUPERVISOR                  172
DOCUMENTO IDENTIFICACIÓN     53
FECHA DE INICIO              51
SUBGRUPO                     10
FECHA DE TERMINACIÓN          9
GRUPO                         4
ESTADO                        0
LUGAR DE EJECUCIÓN            0
NOMBRE CONTRATISTA            0
NÚMERO DE CONTRATO            0
HOJA                          0
dtype: int64

Estructuracion de filas vacias como titulos

In [4]:
import pandas as pd
import unicodedata
import difflib

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# ==========================================================
# CONFIGURACIÓN
# ==========================================================
path_sae = r"input/base_sae.xlsx"
path_rep = r"input/base_reparto.xlsx"

sheet_sae = "EXPEDIENTES"   # Ajusta si es necesario
sheet_rep = 0               # Ajusta si es necesario

col_sae = "RESPONSABLE"
col_rep = "NOMBRE CONTRATISTA"

# ==========================================================
# 1️⃣ LEER RAW SIN HEADER
# ==========================================================
sae_raw = pd.read_excel(path_sae, sheet_name=sheet_sae, header=None, engine="openpyxl")
rep_raw = pd.read_excel(path_rep, sheet_name=sheet_rep, header=None, engine="openpyxl")

print("SAE RAW:", sae_raw.shape)
print("REPARTO RAW:", rep_raw.shape)

# ==========================================================
# 2️⃣ DETECTAR HEADER AUTOMÁTICO
# ==========================================================
def detectar_header(df_raw, palabra_clave, max_scan=120):
    for i in range(min(max_scan, len(df_raw))):
        fila = df_raw.iloc[i].astype(str).str.upper()
        if fila.str.contains(palabra_clave.upper(), na=False).any():
            return i
    raise ValueError(f"No se encontró '{palabra_clave}' en las primeras {max_scan} filas.")

header_sae = detectar_header(sae_raw, col_sae)
header_rep = detectar_header(rep_raw, col_rep)

print("Header SAE detectado en fila:", header_sae)
print("Header REPARTO detectado en fila:", header_rep)

# ==========================================================
# 3️⃣ RECARGAR CON HEADER CORRECTO
# ==========================================================
df_sae = pd.read_excel(path_sae, sheet_name=sheet_sae, header=header_sae, engine="openpyxl")
df_rep = pd.read_excel(path_rep, sheet_name=sheet_rep, header=header_rep, engine="openpyxl")

# ==========================================================
# 4️⃣ LIMPIEZA ESTRUCTURAL
# ==========================================================
def limpiar_df(df):
    df_out = df.copy()
    df_out.columns = df_out.columns.astype(str).str.strip()
    df_out = df_out.loc[:, ~df_out.columns.str.contains("^Unnamed", case=False)]
    df_out = df_out.dropna(how="all")
    df_out = df_out.dropna(axis=1, how="all")
    df_out = df_out.reset_index(drop=True)
    return df_out

df_sae = limpiar_df(df_sae)
df_rep = limpiar_df(df_rep)

print("SAE limpio:", df_sae.shape)
print("REPARTO limpio:", df_rep.shape)

print("Columnas SAE:", df_sae.columns.tolist())
print("Columnas REPARTO:", df_rep.columns.tolist())

# ==========================================================
# 5️⃣ VALIDAR COLUMNAS CLAVE
# ==========================================================
if col_sae not in df_sae.columns:
    raise KeyError(f"❌ No existe '{col_sae}' en SAE")

if col_rep not in df_rep.columns:
    raise KeyError(f"❌ No existe '{col_rep}' en REPARTO")

print("✅ Columnas clave verificadas")

# ==========================================================
# 6️⃣ NORMALIZAR LLAVES
# ==========================================================
def norm_key(x):
    x = "" if x is None else str(x)
    x = x.strip().upper()
    x = " ".join(x.split())
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("ascii")
    return x

df_sae["_RESPONSABLE_NORM"] = df_sae[col_sae].apply(norm_key)
df_rep["_CONTRATISTA_NORM"] = df_rep[col_rep].apply(norm_key)

# ==========================================================
# 7️⃣ VALIDACIÓN DE COBERTURA
# ==========================================================
sae_set = set(df_sae["_RESPONSABLE_NORM"].dropna().unique())
rep_set = set(df_rep["_CONTRATISTA_NORM"].dropna().unique())

sae_set.discard("")
rep_set.discard("")

inter = sae_set.intersection(rep_set)
solo_sae = sorted(list(sae_set - rep_set))
solo_rep = sorted(list(rep_set - sae_set))

print("\n📊 VALIDACIÓN DE COBERTURA")
print("Unicos SAE:", len(sae_set))
print("Unicos REPARTO:", len(rep_set))
print("Coincidencias exactas:", len(inter))
print("Solo en SAE:", len(solo_sae))
print("Solo en REPARTO:", len(solo_rep))

# ==========================================================
# 8️⃣ MERGE PRINCIPAL
# ==========================================================
merge_df = df_sae.merge(
    df_rep,
    left_on="_RESPONSABLE_NORM",
    right_on="_CONTRATISTA_NORM",
    how="left",
    suffixes=("_SAE", "_REPARTO")
)

print("\nMerge realizado:", merge_df.shape)

# ==========================================================
# 9️⃣ SAE SIN ASIGNACIÓN
# ==========================================================
no_asignados_sae = merge_df[merge_df["_CONTRATISTA_NORM"].isna()].copy()

print("SAE sin asignación:", no_asignados_sae.shape[0])

no_asignados_unicos = (
    no_asignados_sae[[col_sae, "_RESPONSABLE_NORM"]]
    .drop_duplicates()
    .sort_values(col_sae)
)

display(no_asignados_unicos.head(50))

# ==========================================================
# 🔟 REPARTO QUE NO EXISTE EN SAE
# ==========================================================
rep_no_en_sae = df_rep[~df_rep["_CONTRATISTA_NORM"].isin(sae_set)].copy()

print("REPARTO que no aparece en SAE:", rep_no_en_sae.shape[0])

display(
    rep_no_en_sae[[col_rep, "_CONTRATISTA_NORM"]]
    .drop_duplicates()
    .sort_values(col_rep)
    .head(50)
)

# ==========================================================
# 1️⃣1️⃣ SUGERENCIAS POR SIMILITUD
# ==========================================================
rep_list = sorted(list(rep_set))

def sugerir_match(nombre_norm, candidatos, n=5, cutoff=0.75):
    if not nombre_norm:
        return []
    return difflib.get_close_matches(nombre_norm, candidatos, n=n, cutoff=cutoff)

sug = no_asignados_unicos.copy()
sug["SUGERENCIAS_REPARTO"] = sug["_RESPONSABLE_NORM"].apply(
    lambda x: sugerir_match(x, rep_list)
)

print("\nSugerencias generadas para revisión manual")
display(sug.head(50))

SAE RAW: (120588, 11)
REPARTO RAW: (359, 12)
Header SAE detectado en fila: 3
Header REPARTO detectado en fila: 0
SAE limpio: (120584, 11)
REPARTO limpio: (358, 12)
Columnas SAE: ['EXPEDIENTE', 'TIPO TRÁMITE', 'TRÁMITE', 'ESTADO ACTUAL', 'REGIONAL', 'FECHA APERTURA', 'ETAPA', 'ACTIVIDAD', 'RESPONSABLE', 'OFICINA RESPONSABLE', 'ES MINERO']
Columnas REPARTO: ['ESTADO', 'NOMBRE CONTRATISTA', 'DOCUMENTO IDENTIFICACIÓN', 'LUGAR DE EJECUCIÓN', 'GRUPO', 'SUBGRUPO', 'CTO B', 'NÚMERO DE CONTRATO', 'FECHA DE INICIO', 'FECHA DE TERMINACIÓN', 'SUPERVISOR', 'HOJA']
✅ Columnas clave verificadas

📊 VALIDACIÓN DE COBERTURA
Unicos SAE: 1307
Unicos REPARTO: 358
Coincidencias exactas: 249
Solo en SAE: 1058
Solo en REPARTO: 109

Merge realizado: (120584, 25)
SAE sin asignación: 110157

                                 RESPONSABLE                     _RESPONSABLE_NORM
119486           FRANCY KATHERINE MORA AMAYA           FRANCY KATHERINE MORA AMAYA
71405                ADALINA  RIVERA GALEANO                ADALINA RIVERA GALEANO
2173           ADRIANA BEATRIZ  ARIAS  VARON           ADRIANA BEATRIZ ARIAS VARON
44036        ADRIANA IVONNE GARCIA RODRIGUEZ       ADRIANA IVONNE GARCIA RODRIGUEZ
50685               ALBA AZUCENA PEÑA GARZON              ALBA AZUCENA PENA GARZON
44165              ALCIRA   RAMIREZ  ESCOBAR                ALCIRA RAMIREZ ESCOBAR
98454               ALEJANDRA  ACOSTA  ACERO                ALEJANDRA ACOSTA ACERO
32925           ALEJANDRO FIQUITIVA CASALLAS          ALEJANDRO FIQUITIVA CASALLAS
32659            ALEXANDER  CAICEDO PULGARIN            ALEXANDER CAICEDO PULGARIN
11208               ALEXANDER  FORERO FORERO               ALEXANDER FORERO FORERO
40081                ALEXIS FAJARDO AGUILERA               ALEXIS FAJARDO AGUILERA
57920        ALFONSO LIBORIO GARCIA PESCADOR       ALFONSO LIBORIO GARCIA PESCADOR
61772                  ALFONSO PULIDO MORENO                 ALFONSO PULIDO MORENO
27756               ALFREDO  BARRETO CARDONA               ALFREDO BARRETO CARDONA
115806         ALVARO FERNANDO GARCIA MONROY         ALVARO FERNANDO GARCIA MONROY
2857              ANA BEATRIZ MONTERO ROMERO            ANA BEATRIZ MONTERO ROMERO
68680            ANA MARIA CUBILLOS  LIEVANO            ANA MARIA CUBILLOS LIEVANO
65795                ANA MARIA DIAZ TRUJILLO               ANA MARIA DIAZ TRUJILLO
56361                 ANA MARIA MUÑOZ ROMERO                ANA MARIA MUNOZ ROMERO
128                   ANA ROCIO CRUZ ALVAREZ                ANA ROCIO CRUZ ALVAREZ
94829         ANA VIRGINIA RODRIGUEZ NAVARRO        ANA VIRGINIA RODRIGUEZ NAVARRO
83568               ANDERSON JOSEPH CASTILLO              ANDERSON JOSEPH CASTILLO
10520            ANDREA  CASTIBLANCO CABRERA            ANDREA CASTIBLANCO CABRERA
117719       ANDREA  CLAUDIA MARTIN MARTINEZ        ANDREA CLAUDIA MARTIN MARTINEZ
66584      ANDREA  DAYANNA MURILLO  LABRADOR       ANDREA DAYANNA MURILLO LABRADOR
113136    ANDREA  DEL PILAR ZAMORA  ALVARADO      ANDREA DEL PILAR ZAMORA ALVARADO
91230                 ANDREA  TORRES SANTANA                 ANDREA TORRES SANTANA
43325                 ANDREA  ZULUAGA FORERO                 ANDREA ZULUAGA FORERO
50548         ANDREA CATALINA CUBILLOS GALLO        ANDREA CATALINA CUBILLOS GALLO
90103     ANDREA LILIANA GONZALEZ  RODRIGUEZ     ANDREA LILIANA GONZALEZ RODRIGUEZ
1275                  ANDREA POVEDA QUINTERO                ANDREA POVEDA QUINTERO
97190           ANDRES FELIPE ESCOBAR CEDIEL          ANDRES FELIPE ESCOBAR CEDIEL
83869            ANDRES FELIPE MELO MARTINEZ           ANDRES FELIPE MELO MARTINEZ
31651            ANDRES GUSTAVO PEREZ MEDINA           ANDRES GUSTAVO PEREZ MEDINA
52655         ANDRES MAURICIO RODRIGUEZ NIÑO        ANDRES MAURICIO RODRIGUEZ NINO
74818               ANGEL DANILO DIAZ ENCISO              ANGEL DANILO DIAZ ENCISO
22581            ANGEL OSWALDO ANTONIO PAIBA           ANGEL OSWALDO ANTONIO PAIBA
43795          ANGELA  MARIA  CORTES VASQUEZ           ANGELA MARIA CORTES VASQUEZ
87330         ANGELA  PATRICIA CASTRO  AVILA          ANGELA PATRICIA CASTRO AVILA
117776            ANGELA CAROLINA LEAL RAMOS            ANGELA CAROLINA LEAL RAMOS
33930         ANGELA PATRICIA GUTIERREZ DIAZ        ANGELA PATRICIA GUTIERREZ DIAZ
43480              ANGELA YOLIMA NOVA MOLANO             ANGELA YOLIMA NOVA MOLANO
69124   ANGELICA ESTEFANIA CASTAÑEDA ESCOBAR  ANGELICA ESTEFANIA CASTANEDA ESCOBAR
31874             ANGGIE PAOLA BELTRAN OCHOA            ANGGIE PAOLA BELTRAN OCHOA
117826         ANGIE  NATALIA CHALA  LATORRE           ANGIE NATALIA CHALA LATORRE
45000              ANGIE  PAOLA LEON VANEGAS              ANGIE PAOLA LEON VANEGAS
38145         ANGIE TATIANA VELASQUEZ GALVIS        ANGIE TATIANA VELASQUEZ GALVIS
89750         ANGIE VALENTINA PEÑUELA PORRAS        ANGIE VALENTINA PENUELA PORRAS
3767                          ARCADIO LADINO                        ARCADIO LADINO
54788          ARGELIO DAVID  VARGAS  FRAGOZ           ARGELIO DAVID VARGAS FRAGOZ

REPARTO que no aparece en SAE: 109

                            NOMBRE CONTRATISTA                          _CONTRATISTA_NORM
91                  GLORIA SOFIA OROZCO POSADA                 GLORIA SOFIA OROZCO POSADA
265                ADRIANA PAOLA PUENTES ROJAS                ADRIANA PAOLA PUENTES ROJAS
314                   AISSA NAYIBE LOZANO CRUZ                   AISSA NAYIBE LOZANO CRUZ
197  ALEIDYS ROSA DEL SOCORRO ARMENTA FERREIRA  ALEIDYS ROSA DEL SOCORRO ARMENTA FERREIRA
184            ALEYDA BEYANITH GAVIRIA MONTOYA            ALEYDA BEYANITH GAVIRIA MONTOYA
1                   ANA MARIA GARCIA RODRIGUEZ                 ANA MARIA GARCIA RODRIGUEZ
282                    ANA MARIA GUZMAN ACOSTA                    ANA MARIA GUZMAN ACOSTA
256               ANDREA MILENA MOLINA AGUILAR               ANDREA MILENA MOLINA AGUILAR
254            ANDREA TATIANA BUITRAGO SALAZAR            ANDREA TATIANA BUITRAGO SALAZAR
110                ANDRES VICENTE OSTOS BUSTOS                ANDRES VICENTE OSTOS BUSTOS
121         ANGELA MILENA NAVARRETE MONTENEGRO         ANGELA MILENA NAVARRETE MONTENEGRO
318                   ANGIE NATALY OTAVO GOMEZ                   ANGIE NATALY OTAVO GOMEZ
233                      ARCADIO LADINO LADINO                      ARCADIO LADINO LADINO
210               ARGELIO DAVID VARGAS FRAGOZO               ARGELIO DAVID VARGAS FRAGOZO
313                     ASHLYE BRUGES ARBOLEDA                     ASHLYE BRUGES ARBOLEDA
319               BARBARA MARIA OSPINA ACEVEDO               BARBARA MARIA OSPINA ACEVEDO
320                BRYAM ERNESTO CASTILLO CRUZ                BRYAM ERNESTO CASTILLO CRUZ
321            CAMILA ANDREA JIMENEZ SALAMANCA            CAMILA ANDREA JIMENEZ SALAMANCA
177                      CAMILA APONTE WILCHES                      CAMILA APONTE WILCHES
6                 CAMILO ANDRES BURNEO SANCHEZ               CAMILO ANDRES BURNEO SANCHEZ
93              CAREN ANDREA BELTRAN CASTAÑEDA             CAREN ANDREA BELTRAN CASTANEDA
119                    CARLOS BAUDILLO ALBA R.                    CARLOS BAUDILLO ALBA R.
209                   CATALINA MOSCOSO ALARCON                   CATALINA MOSCOSO ALARCON
284               CESAR ALEJANDRO CANO MENDOZA               CESAR ALEJANDRO CANO MENDOZA
269              CESAR AUGUSTO CANCELADA GOMEZ              CESAR AUGUSTO CANCELADA GOMEZ
281             CLAUDIA ANDREA MARTIN MARTINEZ             CLAUDIA ANDREA MARTIN MARTINEZ
322            CLAUDIA LILIANA RODRIGUEZ LUCAS            CLAUDIA LILIANA RODRIGUEZ LUCAS
96              CRISTIAN ANDRES GODOY GONZÁLEZ             CRISTIAN ANDRES GODOY GONZALEZ
9                      DAISY YOLIMA CASAS RICO                    DAISY YOLIMA CASAS RICO
323                   DANIELA FARFÁN MOLINARES                   DANIELA FARFAN MOLINARES
116                      DANIELA FORERO FORERO                      DANIELA FORERO FORERO
90                 DANILA MERCEDES ARGOTE DAZA                DANILA MERCEDES ARGOTE DAZA
154                        DAVID MENDEZ CAMELO                        DAVID MENDEZ CAMELO
159                DIANA CAROLINA MORERA ACUÑA                DIANA CAROLINA MORERA ACUNA
83               DIANA MARCELA PINILLOS OROZCO              DIANA MARCELA PINILLOS OROZCO
11         DIEGO ALEJANDRO CASTIBLANCO HERRERA        DIEGO ALEJANDRO CASTIBLANCO HERRERA
13                  ELIANA ROCIO PINZON PINZON                 ELIANA ROCIO PINZON PINZON
19                     ELSY TATIANA ARCINIEGAS                    ELSY TATIANA ARCINIEGAS
342                FABIO ALBERTO VEGA GONZALEZ                FABIO ALBERTO VEGA GONZALEZ
279                     HENRY JOSE RIOS GARCIA                     HENRY JOSE RIOS GARCIA
148                INGRID ALEXANDRA BETANCOURT                INGRID ALEXANDRA BETANCOURT
87                   JAIME ALBERTO DUQUE MEJIA                  JAIME ALBERTO DUQUE MEJIA
150                        JAIME GOMEZ CACERES                        JAIME GOMEZ CACERES
122              JAIRO HERNANDO HENANDEZ VIVAS              JAIRO HERNANDO HENANDEZ VIVAS
73                       JENNIFER BERNAL ORTIZ                      JENNIFER BERNAL ORTIZ
296                JENNIFER KARINA AYALA PEREZ                JENNIFER KARINA AYALA PEREZ
147              JENNIFER LILIANA SUAREZ ROJAS              JENNIFER LILIANA SUAREZ ROJAS
164       JENNIFER TATIANA MATALLANA RODRIGUEZ       JENNIFER TATIANA MATALLANA RODRIGUEZ
20               JILMER STEVEN SANCHEZ CARDOZO              JILMER STEVEN SANCHEZ CARDOZO
330             JOHANA CAROLINA RIVERA AGUILAR             JOHANA CAROLINA RIVERA AGUILAR

Sugerencias generadas para revisión manual

                                 RESPONSABLE                     _RESPONSABLE_NORM               SUGERENCIAS_REPARTO
119486           FRANCY KATHERINE MORA AMAYA           FRANCY KATHERINE MORA AMAYA                                []
71405                ADALINA  RIVERA GALEANO                ADALINA RIVERA GALEANO                                []
2173           ADRIANA BEATRIZ  ARIAS  VARON           ADRIANA BEATRIZ ARIAS VARON                                []
44036        ADRIANA IVONNE GARCIA RODRIGUEZ       ADRIANA IVONNE GARCIA RODRIGUEZ      [ANA MARIA GARCIA RODRIGUEZ]
50685               ALBA AZUCENA PEÑA GARZON              ALBA AZUCENA PENA GARZON                                []
44165              ALCIRA   RAMIREZ  ESCOBAR                ALCIRA RAMIREZ ESCOBAR                                []
98454               ALEJANDRA  ACOSTA  ACERO                ALEJANDRA ACOSTA ACERO                                []
32925           ALEJANDRO FIQUITIVA CASALLAS          ALEJANDRO FIQUITIVA CASALLAS                                []
32659            ALEXANDER  CAICEDO PULGARIN            ALEXANDER CAICEDO PULGARIN                                []
11208               ALEXANDER  FORERO FORERO               ALEXANDER FORERO FORERO           [DANIELA FORERO FORERO]
40081                ALEXIS FAJARDO AGUILERA               ALEXIS FAJARDO AGUILERA                                []
57920        ALFONSO LIBORIO GARCIA PESCADOR       ALFONSO LIBORIO GARCIA PESCADOR                                []
61772                  ALFONSO PULIDO MORENO                 ALFONSO PULIDO MORENO                                []
27756               ALFREDO  BARRETO CARDONA               ALFREDO BARRETO CARDONA                                []
115806         ALVARO FERNANDO GARCIA MONROY         ALVARO FERNANDO GARCIA MONROY                                []
2857              ANA BEATRIZ MONTERO ROMERO            ANA BEATRIZ MONTERO ROMERO                                []
68680            ANA MARIA CUBILLOS  LIEVANO            ANA MARIA CUBILLOS LIEVANO                                []
65795                ANA MARIA DIAZ TRUJILLO               ANA MARIA DIAZ TRUJILLO                                []
56361                 ANA MARIA MUÑOZ ROMERO                ANA MARIA MUNOZ ROMERO                                []
128                   ANA ROCIO CRUZ ALVAREZ                ANA ROCIO CRUZ ALVAREZ                                []
94829         ANA VIRGINIA RODRIGUEZ NAVARRO        ANA VIRGINIA RODRIGUEZ NAVARRO                                []
83568               ANDERSON JOSEPH CASTILLO              ANDERSON JOSEPH CASTILLO                                []
10520            ANDREA  CASTIBLANCO CABRERA            ANDREA CASTIBLANCO CABRERA                                []
117719       ANDREA  CLAUDIA MARTIN MARTINEZ        ANDREA CLAUDIA MARTIN MARTINEZ  [CLAUDIA ANDREA MARTIN MARTINEZ]
66584      ANDREA  DAYANNA MURILLO  LABRADOR       ANDREA DAYANNA MURILLO LABRADOR                                []
113136    ANDREA  DEL PILAR ZAMORA  ALVARADO      ANDREA DEL PILAR ZAMORA ALVARADO                                []
91230                 ANDREA  TORRES SANTANA                 ANDREA TORRES SANTANA                                []
43325                 ANDREA  ZULUAGA FORERO                 ANDREA ZULUAGA FORERO                                []
50548         ANDREA CATALINA CUBILLOS GALLO        ANDREA CATALINA CUBILLOS GALLO                                []
90103     ANDREA LILIANA GONZALEZ  RODRIGUEZ     ANDREA LILIANA GONZALEZ RODRIGUEZ                                []
1275                  ANDREA POVEDA QUINTERO                ANDREA POVEDA QUINTERO                                []
97190           ANDRES FELIPE ESCOBAR CEDIEL          ANDRES FELIPE ESCOBAR CEDIEL                                []
83869            ANDRES FELIPE MELO MARTINEZ           ANDRES FELIPE MELO MARTINEZ                                []
31651            ANDRES GUSTAVO PEREZ MEDINA           ANDRES GUSTAVO PEREZ MEDINA                                []
52655         ANDRES MAURICIO RODRIGUEZ NIÑO        ANDRES MAURICIO RODRIGUEZ NINO                                []
74818               ANGEL DANILO DIAZ ENCISO              ANGEL DANILO DIAZ ENCISO                                []
22581            ANGEL OSWALDO ANTONIO PAIBA           ANGEL OSWALDO ANTONIO PAIBA                                []
43795          ANGELA  MARIA  CORTES VASQUEZ           ANGELA MARIA CORTES VASQUEZ                                []
87330         ANGELA  PATRICIA CASTRO  AVILA          ANGELA PATRICIA CASTRO AVILA       [ANGELA PATRICIA ORTIZ AYA]
117776            ANGELA CAROLINA LEAL RAMOS            ANGELA CAROLINA LEAL RAMOS                                []
33930         ANGELA PATRICIA GUTIERREZ DIAZ        ANGELA PATRICIA GUTIERREZ DIAZ       [ANGELA PATRICIA ORTIZ AYA]
43480              ANGELA YOLIMA NOVA MOLANO             ANGELA YOLIMA NOVA MOLANO                                []
69124   ANGELICA ESTEFANIA CASTAÑEDA ESCOBAR  ANGELICA ESTEFANIA CASTANEDA ESCOBAR                                []
31874             ANGGIE PAOLA BELTRAN OCHOA            ANGGIE PAOLA BELTRAN OCHOA                                []
117826         ANGIE  NATALIA CHALA  LATORRE           ANGIE NATALIA CHALA LATORRE                                []
45000              ANGIE  PAOLA LEON VANEGAS              ANGIE PAOLA LEON VANEGAS                                []
38145         ANGIE TATIANA VELASQUEZ GALVIS        ANGIE TATIANA VELASQUEZ GALVIS                                []
89750         ANGIE VALENTINA PEÑUELA PORRAS        ANGIE VALENTINA PENUELA PORRAS                                []
3767                          ARCADIO LADINO                        ARCADIO LADINO           [ARCADIO LADINO LADINO]
54788          ARGELIO DAVID  VARGAS  FRAGOZ           ARGELIO DAVID VARGAS FRAGOZ    [ARGELIO DAVID VARGAS FRAGOZO]

importes y configuracion

In [5]:
import os
import pandas as pd
import unicodedata
import difflib
from datetime import datetime

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# =========================
# CONFIGURACIÓN
# =========================
path_sae = r"input/base_sae.xlsx"
path_rep = r"input/base_reparto.xlsx"

sheet_sae = "EXPEDIENTES"   # ajusta si aplica
sheet_rep = 0               # ajusta si aplica

col_sae = "RESPONSABLE"
col_rep = "NOMBRE CONTRATISTA"

output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

# Archivo final (multi-hoja)
out_xlsx = os.path.join(output_dir, "analisis_grupos_por_persona.xlsx")

Limpieza y normalizacion

In [6]:
def detectar_header(df_raw, palabra_clave, max_scan=200):
    for i in range(min(max_scan, len(df_raw))):
        fila = df_raw.iloc[i].astype(str).str.upper().fillna("")
        if fila.str.contains(palabra_clave.upper(), na=False).any():
            return i
    raise ValueError(f"No se encontró '{palabra_clave}' en las primeras {max_scan} filas.")

def limpiar_df(df):
    out = df.copy()
    out.columns = out.columns.astype(str).str.strip()
    out = out.loc[:, ~out.columns.str.contains(r"^Unnamed", case=False, regex=True)]
    out = out.dropna(how="all")
    out = out.dropna(axis=1, how="all")
    out = out.reset_index(drop=True)
    return out

def norm_key(x):
    x = "" if x is None else str(x)
    x = x.strip().upper()
    x = " ".join(x.split())
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("ascii")
    return x

def sugerir_match(nombre_norm, candidatos, n=5, cutoff=0.75):
    if not nombre_norm:
        return []
    return difflib.get_close_matches(nombre_norm, candidatos, n=n, cutoff=cutoff)

In [7]:
# RAW para detectar header real (quita filas título)
sae_raw = pd.read_excel(path_sae, sheet_name=sheet_sae, header=None, engine="openpyxl", nrows=200)
rep_raw = pd.read_excel(path_rep, sheet_name=sheet_rep, header=None, engine="openpyxl", nrows=200)

header_sae = detectar_header(sae_raw, col_sae)
header_rep = detectar_header(rep_raw, col_rep)

print("Header SAE detectado en fila:", header_sae)
print("Header REPARTO detectado en fila:", header_rep)

# Cargar definitivo con header correcto
df_sae = limpiar_df(pd.read_excel(path_sae, sheet_name=sheet_sae, header=header_sae, engine="openpyxl"))
df_rep = limpiar_df(pd.read_excel(path_rep, sheet_name=sheet_rep, header=header_rep, engine="openpyxl"))

print("SAE:", df_sae.shape)
print("REPARTO:", df_rep.shape)

# Validar columnas clave
if col_sae not in df_sae.columns:
    raise KeyError(f"SAE: no existe '{col_sae}'. Columnas: {df_sae.columns.tolist()}")
if col_rep not in df_rep.columns:
    raise KeyError(f"REPARTO: no existe '{col_rep}'. Columnas: {df_rep.columns.tolist()}")

display(df_sae.head(5))
display(df_rep.head(5))

Header SAE detectado en fila: 3
Header REPARTO detectado en fila: 0
SAE: (120584, 11)
REPARTO: (358, 12)

,EXPEDIENTE,TIPO TRÁMITE,TRÁMITE,ESTADO ACTUAL,REGIONAL,FECHA APERTURA,ETAPA,ACTIVIDAD,RESPONSABLE,OFICINA RESPONSABLE,ES MINERO
0,1,Permisivo,Concesión de Aguas Superficiales,Seguimiento y Control,Sabana Centro,1945-02-01,Seguimiento y Control,Acto Administrativo,FORERO FORERO DANIELA,Sabana Centro,NO
1,2,Permisivo,Concesión de Aguas Superficiales,Archivado,Ubate,1948-03-15,Archivado,Archivado,No Aplica,Ubate,NO
2,3,Permisivo,Plan de Manejo Ambiental,Archivado,Sabana Centro,1951-11-22,Archivado,Archivado,No Aplica,Sabana Centro,NO
3,4,Permisivo,Concesión de Aguas Superficiales,Archivado,Ubate,1954-11-25,Archivado,Archivado,No Aplica,Ubate,NO
4,5,Permisivo,Permiso de Extracción Material de Arrastre,Archivado,Bajo Magdalena,1955-09-23,Archivado,Archivado,No Aplica,Bajo Magdalena,NO

,ESTADO,NOMBRE CONTRATISTA,DOCUMENTO IDENTIFICACIÓN,LUGAR DE EJECUCIÓN,GRUPO,SUBGRUPO,CTO B,NÚMERO DE CONTRATO,FECHA DE INICIO,FECHA DE TERMINACIÓN,SUPERVISOR,HOJA
0,EN EJECUCIÓN,MONICA ALEJANDRA CAMARGO SILVA,1000326898,BOGOTÁ LA CALERA,JUDICANTES,JUDICANTES,NaN,20,2026-01-14 00:00:00,2026-11-13,YUBER YESID CARDENAS PULIDO Director Regional,CTOS NUEVOS 2026
1,CONTRATO PUBLICADO,ANA MARIA GARCIA RODRIGUEZ,1072752326,BAJO MAGDALENA,12.2.4 SAE,APOYO SAE,NaN,976,2026-01-20 00:00:00,2026-06-30,JUAN FILIVERTO COTRINO GUEVARA DIRECTOR ...,CTOS NUEVOS 2026
2,EN EJECUCIÓN,LUCERO DÍAZ ARROYO,1104768,SUBDIRECCIÓN,NaN,NaN,NaN,1132,2026-01-29 00:00:00,2026-06-30,BRAYAN GUILLERMO MARTINEZ Subdirector General...,CTOS NUEVOS 2026
3,EN EJECUCIÓN,ANGELA ALEJANDRA NIÑO PINZÓN,1019069831,SABANA CENTRO,12.2.3 RESUELTO,NOTIFICADOR,NaN,982,2026-01-29 00:00:00,2026-06-30,ANDRES MAURICIO GARZON ORJUELA DIRECTOR REGI...,CTOS NUEVOS 2026
4,CONTRATO PUBLICADO,ANGELA MARIA BEDOYA GONZALEZ,41950886,DIRECCIÓN JURÍDICA,12.2.1 EN TRÁMITE,SUSTACIADOR - REVISOR,NaN,768,2026-01-29 00:00:00,2026-06-30,JHOANNA ALEXANDRA MONTOYA MUÑOZ ...,CTOS NUEVOS 2026

Definifr casillas E,F,G

In [8]:
# Normalizar llaves
df_sae["_RESPONSABLE_NORM"] = df_sae[col_sae].apply(norm_key)
df_rep["_CONTRATISTA_NORM"] = df_rep[col_rep].apply(norm_key)

# E/F/G por posición (después de limpieza)
rep_cols = df_rep.columns.tolist()
if len(rep_cols) < 7:
    raise ValueError(f"REPARTO no tiene suficientes columnas para tomar E/F/G por posición. Columnas: {rep_cols}")

col_E, col_F, col_G = rep_cols[4], rep_cols[5], rep_cols[6]
efg_cols = [col_E, col_F, col_G]

print("✅ Columnas E/F/G detectadas por posición:")
print("E =", col_E)
print("F =", col_F)
print("G =", col_G)

✅ Columnas E/F/G detectadas por posición:
E = GRUPO
F = SUBGRUPO
G = CTO B

MARGE

In [9]:
# Subset reparto con E/F/G
rep_keep = [col_rep, "_CONTRATISTA_NORM"] + efg_cols
df_rep_small = df_rep[rep_keep].copy()

# SAE mínimo para relación
df_sae_small = df_sae[[col_sae, "_RESPONSABLE_NORM"]].copy()

# Merge SAE <- Reparto
merge_df = df_sae_small.merge(
    df_rep_small,
    left_on="_RESPONSABLE_NORM",
    right_on="_CONTRATISTA_NORM",
    how="left"
)

# Duplicados en reparto
dups_rep = df_rep_small["_CONTRATISTA_NORM"].value_counts()
dups_rep = dups_rep[dups_rep > 1].rename("conteo").reset_index().rename(columns={"index":"_CONTRATISTA_NORM"})
dup_set = set(dups_rep["_CONTRATISTA_NORM"].tolist()) if not dups_rep.empty else set()

# Crear estado match
merge_df["ESTADO_MATCH"] = merge_df["_CONTRATISTA_NORM"].apply(
    lambda x: "ASIGNADO" if isinstance(x, str) and x.strip() != "" else "NO_ASIGNADO"
)
merge_df["REPARTO_DUPLICADO"] = merge_df["_CONTRATISTA_NORM"].apply(lambda x: "SI" if x in dup_set else "NO")

# Texto amigable de grupo (E/F/G)
def armar_grupo(row):
    if row["ESTADO_MATCH"] != "ASIGNADO":
        return "NO ASIGNADO"
    e = str(row.get(col_E, "")).strip()
    f = str(row.get(col_F, "")).strip()
    g = str(row.get(col_G, "")).strip()
    return f"E: {e} | F: {f} | G: {g}"

merge_df["GRUPO_DEFINIDO"] = merge_df.apply(armar_grupo, axis=1)

# RELACION: 1 fila por responsable (si SAE tiene repetidos, quedamos con la primera)
relacion = merge_df.drop_duplicates(subset=["_RESPONSABLE_NORM"]).reset_index(drop=True)

display(relacion.head(20))

,RESPONSABLE,_RESPONSABLE_NORM,NOMBRE CONTRATISTA,_CONTRATISTA_NORM,GRUPO,SUBGRUPO,CTO B,ESTADO_MATCH,REPARTO_DUPLICADO,GRUPO_DEFINIDO
0,FORERO FORERO DANIELA,FORERO FORERO DANIELA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
1,No Aplica,NO APLICA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
2,NaN,NAN,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
3,Alejandra Liliana Torres Benitez,ALEJANDRA LILIANA TORRES BENITEZ,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
4,Andres Mauricio Garzon Orjuela,ANDRES MAURICIO GARZON ORJUELA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
5,ASHLYE ESPERANZA BRUGES ARBOLEDA,ASHLYE ESPERANZA BRUGES ARBOLEDA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
6,ANA ROCIO CRUZ ALVAREZ,ANA ROCIO CRUZ ALVAREZ,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
7,Sergio Felipe Torres Calderón,SERGIO FELIPE TORRES CALDERON,SERGIO FELIPE TORRES CALDERON,SERGIO FELIPE TORRES CALDERON,12.2.5 SEGUIMIENTO Y CONTROL,SUSTANCIADOR,NaN,ASIGNADO,NO,E: 12.2.5 SEGUIMIENTO Y CONTROL | F: SUSTANCIA...
8,JULIO ALBERTO MALDONADO RODRIGUEZ,JULIO ALBERTO MALDONADO RODRIGUEZ,JULIO ALBERTO MALDONADO RODRIGUEZ,JULIO ALBERTO MALDONADO RODRIGUEZ,12.2.5 SEGUIMIENTO Y CONTROL,SUSTANCIADOR,NaN,ASIGNADO,NO,E: 12.2.5 SEGUIMIENTO Y CONTROL | F: SUSTANCIA...
9,ANDRES FELIPE BARRETO PRADA,ANDRES FELIPE BARRETO PRADA,ANDRES FELIPE BARRETO PRADA,ANDRES FELIPE BARRETO PRADA,12.2.5 SEGUIMIENTO Y CONTROL,SUSTANCIADOR,NaN,ASIGNADO,NO,E: 12.2.5 SEGUIMIENTO Y CONTROL | F: SUSTANCIA...
10,Julian Andres Echeverril Lopez,JULIAN ANDRES ECHEVERRIL LOPEZ,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
11,Marcela Del Pilar Aranguren Sanabria,MARCELA DEL PILAR ARANGUREN SANABRIA,MARCELA DEL PILAR ARANGUREN SANABRIA,MARCELA DEL PILAR ARANGUREN SANABRIA,12.2.5 SEGUIMIENTO Y CONTROL,SUSTANCIADOR SENIOR,NaN,ASIGNADO,NO,E: 12.2.5 SEGUIMIENTO Y CONTROL | F: SUSTANCIA...
12,CARLOS FELIPE SANCHEZ GOMEZ,CARLOS FELIPE SANCHEZ GOMEZ,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
13,SILVIA PATRICIA MESA HERRERA,SILVIA PATRICIA MESA HERRERA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
14,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,12.2.5 SEGUIMIENTO Y CONTROL,SUSTANCIADOR,NaN,ASIGNADO,NO,E: 12.2.5 SEGUIMIENTO Y CONTROL | F: SUSTANCIA...
15,KAROLL NATALIA ORTEGA CASAS,KAROLL NATALIA ORTEGA CASAS,KAROLL NATALIA ORTEGA CASAS,KAROLL NATALIA ORTEGA CASAS,12.2.1 EN TRÁMITE,SUSTANCIADOR SENIOR,NaN,ASIGNADO,NO,E: 12.2.1 EN TRÁMITE | F: SUSTANCIADOR SENIOR ...
16,Xiomara Chacon Martinez,XIOMARA CHACON MARTINEZ,XIOMARA CHACON MARTINEZ,XIOMARA CHACON MARTINEZ,12.2.1 EN TRÁMITE,SUSTANCIADOR,NaN,ASIGNADO,NO,E: 12.2.1 EN TRÁMITE | F: SUSTANCIADOR | G: nan
17,Diana Carolina Forero Moyano,DIANA CAROLINA FORERO MOYANO,DIANA CAROLINA FORERO MOYANO,DIANA CAROLINA FORERO MOYANO,12.2.1 EN TRÁMITE,INVERSIÓN,NaN,ASIGNADO,NO,E: 12.2.1 EN TRÁMITE | F: INVERSIÓN | G: nan
18,JENNIFFER LILIANA SUAREZ ROJAS,JENNIFFER LILIANA SUAREZ ROJAS,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO
19,Johan Sebastián Ramírez Nocua,JOHAN SEBASTIAN RAMIREZ NOCUA,NaN,NaN,NaN,NaN,NaN,NO_ASIGNADO,NO,NO ASIGNADO

VALIDACION DE RUIDO DE DATOS

In [10]:
# Sets para análisis
sae_set = set(df_sae_small["_RESPONSABLE_NORM"].dropna().unique()); sae_set.discard("")
rep_set = set(df_rep_small["_CONTRATISTA_NORM"].dropna().unique()); rep_set.discard("")
inter = sae_set & rep_set

# No asignados (SAE)
no_asignados = relacion[relacion["ESTADO_MATCH"] == "NO_ASIGNADO"][[col_sae, "_RESPONSABLE_NORM"]].copy()
no_asignados = no_asignados.drop_duplicates().sort_values(col_sae).reset_index(drop=True)

# Reparto no aparece en SAE
rep_no_en_sae = df_rep_small[~df_rep_small["_CONTRATISTA_NORM"].isin(sae_set)].copy()
rep_no_en_sae = rep_no_en_sae.drop_duplicates(subset=["_CONTRATISTA_NORM"]).reset_index(drop=True)

# Sugerencias para no asignados
rep_list = sorted(list(rep_set))
sugerencias = no_asignados.copy()
sugerencias["SUGERENCIAS_REPARTO"] = sugerencias["_RESPONSABLE_NORM"].apply(
    lambda x: sugerir_match(x, rep_list, n=5, cutoff=0.75)
)

display(no_asignados.head(30))
display(sugerencias.head(30))
display(rep_no_en_sae.head(30))

                           RESPONSABLE                  _RESPONSABLE_NORM
0          FRANCY KATHERINE MORA AMAYA        FRANCY KATHERINE MORA AMAYA
1              ADALINA  RIVERA GALEANO             ADALINA RIVERA GALEANO
2        ADRIANA BEATRIZ  ARIAS  VARON        ADRIANA BEATRIZ ARIAS VARON
3      ADRIANA IVONNE GARCIA RODRIGUEZ    ADRIANA IVONNE GARCIA RODRIGUEZ
4             ALBA AZUCENA PEÑA GARZON           ALBA AZUCENA PENA GARZON
5            ALCIRA   RAMIREZ  ESCOBAR             ALCIRA RAMIREZ ESCOBAR
6             ALEJANDRA  ACOSTA  ACERO             ALEJANDRA ACOSTA ACERO
7         ALEJANDRO FIQUITIVA CASALLAS       ALEJANDRO FIQUITIVA CASALLAS
8          ALEXANDER  CAICEDO PULGARIN         ALEXANDER CAICEDO PULGARIN
9             ALEXANDER  FORERO FORERO            ALEXANDER FORERO FORERO
10             ALEXIS FAJARDO AGUILERA            ALEXIS FAJARDO AGUILERA
11     ALFONSO LIBORIO GARCIA PESCADOR    ALFONSO LIBORIO GARCIA PESCADOR
12               ALFONSO PULIDO MORENO              ALFONSO PULIDO MORENO
13            ALFREDO  BARRETO CARDONA            ALFREDO BARRETO CARDONA
14       ALVARO FERNANDO GARCIA MONROY      ALVARO FERNANDO GARCIA MONROY
15          ANA BEATRIZ MONTERO ROMERO         ANA BEATRIZ MONTERO ROMERO
16         ANA MARIA CUBILLOS  LIEVANO         ANA MARIA CUBILLOS LIEVANO
17             ANA MARIA DIAZ TRUJILLO            ANA MARIA DIAZ TRUJILLO
18              ANA MARIA MUÑOZ ROMERO             ANA MARIA MUNOZ ROMERO
19              ANA ROCIO CRUZ ALVAREZ             ANA ROCIO CRUZ ALVAREZ
20      ANA VIRGINIA RODRIGUEZ NAVARRO     ANA VIRGINIA RODRIGUEZ NAVARRO
21            ANDERSON JOSEPH CASTILLO           ANDERSON JOSEPH CASTILLO
22         ANDREA  CASTIBLANCO CABRERA         ANDREA CASTIBLANCO CABRERA
23     ANDREA  CLAUDIA MARTIN MARTINEZ     ANDREA CLAUDIA MARTIN MARTINEZ
24   ANDREA  DAYANNA MURILLO  LABRADOR    ANDREA DAYANNA MURILLO LABRADOR
25  ANDREA  DEL PILAR ZAMORA  ALVARADO   ANDREA DEL PILAR ZAMORA ALVARADO
26              ANDREA  TORRES SANTANA              ANDREA TORRES SANTANA
27              ANDREA  ZULUAGA FORERO              ANDREA ZULUAGA FORERO
28      ANDREA CATALINA CUBILLOS GALLO     ANDREA CATALINA CUBILLOS GALLO
29  ANDREA LILIANA GONZALEZ  RODRIGUEZ  ANDREA LILIANA GONZALEZ RODRIGUEZ

                           RESPONSABLE                  _RESPONSABLE_NORM               SUGERENCIAS_REPARTO
0          FRANCY KATHERINE MORA AMAYA        FRANCY KATHERINE MORA AMAYA                                []
1              ADALINA  RIVERA GALEANO             ADALINA RIVERA GALEANO                                []
2        ADRIANA BEATRIZ  ARIAS  VARON        ADRIANA BEATRIZ ARIAS VARON                                []
3      ADRIANA IVONNE GARCIA RODRIGUEZ    ADRIANA IVONNE GARCIA RODRIGUEZ      [ANA MARIA GARCIA RODRIGUEZ]
4             ALBA AZUCENA PEÑA GARZON           ALBA AZUCENA PENA GARZON                                []
5            ALCIRA   RAMIREZ  ESCOBAR             ALCIRA RAMIREZ ESCOBAR                                []
6             ALEJANDRA  ACOSTA  ACERO             ALEJANDRA ACOSTA ACERO                                []
7         ALEJANDRO FIQUITIVA CASALLAS       ALEJANDRO FIQUITIVA CASALLAS                                []
8          ALEXANDER  CAICEDO PULGARIN         ALEXANDER CAICEDO PULGARIN                                []
9             ALEXANDER  FORERO FORERO            ALEXANDER FORERO FORERO           [DANIELA FORERO FORERO]
10             ALEXIS FAJARDO AGUILERA            ALEXIS FAJARDO AGUILERA                                []
11     ALFONSO LIBORIO GARCIA PESCADOR    ALFONSO LIBORIO GARCIA PESCADOR                                []
12               ALFONSO PULIDO MORENO              ALFONSO PULIDO MORENO                                []
13            ALFREDO  BARRETO CARDONA            ALFREDO BARRETO CARDONA                                []
14       ALVARO FERNANDO GARCIA MONROY      ALVARO FERNANDO GARCIA MONROY                                []
15          ANA BEATRIZ MONTERO ROMERO         ANA BEATRIZ MONTERO ROMERO                                []
16         ANA MARIA CUBILLOS  LIEVANO         ANA MARIA CUBILLOS LIEVANO                                []
17             ANA MARIA DIAZ TRUJILLO            ANA MARIA DIAZ TRUJILLO                                []
18              ANA MARIA MUÑOZ ROMERO             ANA MARIA MUNOZ ROMERO                                []
19              ANA ROCIO CRUZ ALVAREZ             ANA ROCIO CRUZ ALVAREZ                                []
20      ANA VIRGINIA RODRIGUEZ NAVARRO     ANA VIRGINIA RODRIGUEZ NAVARRO                                []
21            ANDERSON JOSEPH CASTILLO           ANDERSON JOSEPH CASTILLO                                []
22         ANDREA  CASTIBLANCO CABRERA         ANDREA CASTIBLANCO CABRERA                                []
23     ANDREA  CLAUDIA MARTIN MARTINEZ     ANDREA CLAUDIA MARTIN MARTINEZ  [CLAUDIA ANDREA MARTIN MARTINEZ]
24   ANDREA  DAYANNA MURILLO  LABRADOR    ANDREA DAYANNA MURILLO LABRADOR                                []
25  ANDREA  DEL PILAR ZAMORA  ALVARADO   ANDREA DEL PILAR ZAMORA ALVARADO                                []
26              ANDREA  TORRES SANTANA              ANDREA TORRES SANTANA                                []
27              ANDREA  ZULUAGA FORERO              ANDREA ZULUAGA FORERO                                []
28      ANDREA CATALINA CUBILLOS GALLO     ANDREA CATALINA CUBILLOS GALLO                                []
29  ANDREA LILIANA GONZALEZ  RODRIGUEZ  ANDREA LILIANA GONZALEZ RODRIGUEZ                                []

                     NOMBRE CONTRATISTA                    _CONTRATISTA_NORM                          GRUPO                   SUBGRUPO                       CTO B
0            ANA MARIA GARCIA RODRIGUEZ           ANA MARIA GARCIA RODRIGUEZ                    12.2.4 SAE                   APOYO SAE                         NaN
1                    LUCERO DÍAZ ARROYO                   LUCERO DIAZ ARROYO                            NaN                        NaN                         NaN
2          CAMILO ANDRES BURNEO SANCHEZ         CAMILO ANDRES BURNEO SANCHEZ                   12.2.6 UIGA   APOYO ADMINISTRATIVO UIGA                         NaN
3               DAISY YOLIMA CASAS RICO              DAISY YOLIMA CASAS RICO                   12.2.6 UIGA               ABOGADOS UIGA                         NaN
4   DIEGO ALEJANDRO CASTIBLANCO HERRERA  DIEGO ALEJANDRO CASTIBLANCO HERRERA                        SIGESPU                    SIGESPU                         NaN
5            ELIANA ROCIO PINZON PINZON           ELIANA ROCIO PINZON PINZON                    12.2.4 SAE                   APOYO SAE                         NaN
6      JOSEFINA BERNARDA QUINTERO ANAYA     JOSEFINA BERNARDA QUINTERO ANAYA                   12.2.6 UIGA               ABOGADOS UIGA                         NaN
7                 KAREN OSORIO BUITRAGO                KAREN OSORIO BUITRAGO               12.2.3 RESUELTO                 NOTIFICADOR                         NaN
8               ELSY TATIANA ARCINIEGAS              ELSY TATIANA ARCINIEGAS             12.2.1 EN TRÁMITE         SUSTANCIADOR SENIOR  OBLIGACIONES NUEVAS 12.2.1
9         JILMER STEVEN SANCHEZ CARDOZO        JILMER STEVEN SANCHEZ CARDOZO                    12.2.4 SAE                     ENLACES                         NaN
10       MANUEL FERNANDO GOMEZ LANDINEZ       MANUEL FERNANDO GOMEZ LANDINEZ                   12.2.6 UIGA               ABOGADOS UIGA                         NaN
11              MARIO HERNANDEZ SANCHEZ              MARIO HERNANDEZ SANCHEZ                   12.2.6 UIGA             INGENIEROS UIGA                         NaN
12               NANCY LICET MORA UMAÑA               NANCY LICET MORA UMANA                   12.2.6 UIGA               ABOGADOS UIGA                         NaN
13               NUBIA ANTOLINEZ ALDANA               NUBIA ANTOLINEZ ALDANA                    12.2.4 SAE                   APOYO SAE                         NaN
14                 OMAIRA ROJAS SANCHEZ                 OMAIRA ROJAS SANCHEZ                    12.2.4 SAE                   APOYO SAE                         NaN
15            PAOLA ALEJANDRA VERA VERA            PAOLA ALEJANDRA VERA VERA                    12.2.4 SAE                   APOYO SAE                         NaN
16        PEDRO ANTONIO CORREDOR VARGAS        PEDRO ANTONIO CORREDOR VARGAS     PRESUPUESTO Y CONTRATACIÓN                PRESUPUESTO                         NaN
17      RICARDO YECID CALDERON BEJARANO      RICARDO YECID CALDERON BEJARANO                   12.2.6 UIGA               ABOGADOS UIGA                         NaN
18              VLADIMIR BRAVO GONZALEZ              VLADIMIR BRAVO GONZALEZ                    12.2.4 SAE                   APOYO SAE                         NaN
19                  SANDRA YISEL BORBON                  SANDRA YISEL BORBON             12.2.1 EN TRÁMITE       REVISOR SANCIONATORIO                         NaN
20               YAYLENNE ORTIZ VERGARA               YAYLENNE ORTIZ VERGARA                   12.2.6 UIGA             INGENIEROS UIGA                         NaN
21           RENE PERILLA CASTELBLANCO             RENE PERILLA CASTELBLANCO                    12.2.4 SAE                     ENLACES                         NaN
22              VALENTINA BERNAL TRIANA              VALENTINA BERNAL TRIANA               12.2.3 RESUELTO                 NOTIFICADOR                         NaN
23             JOHN WILMAR TOVAR CHAVEZ             JOHN WILMAR TOVAR CHAVEZ  12.2.5 SEGUIMIENTO Y CONTROL                SUSTANCIADOR                         NaN
24                SAYDI SANCHEZ CAMACHO                SAYDI SANCHEZ CAMACHO             12.2.1 EN TRÁMITE         SUSTANCIADOR SENIOR                         NaN
25          MARYORIS CARRILLO ESMERALDA          MARYORIS CARRILLO ESMERALDA             12.2.1 EN TRÁMITE       REVISOR SANCIONATORIO                         NaN
26       SHARON GUISEELLE CONTRERAS REY       SHARON GUISEELLE CONTRERAS REY             12.2.1 EN TRÁMITE       REVISOR SANCIONATORIO                         NaN
27   YENNIFER ALEXANDRA CABALLERO ARIAS   YENNIFER ALEXANDRA CABALLERO ARIAS                   CONTRATACIÓN               CONTRATACIÓN                         NaN
28                JENNIFER BERNAL ORTIZ                JENNIFER BERNAL ORTIZ                   12.2.6 UIGA             INGENIEROS UIGA                         NaN
29           LILIAN BIBIANA ROJAS MEJIA           LILIAN BIBIANA ROJAS MEJIA                   12.2.6 UIGA               ABOGADOS UIGA                         NaN

In [11]:
resumen_df = pd.DataFrame({
    "Metrica": [
        "Personas únicas SAE",
        "Contratistas únicos Reparto",
        "Coincidencias exactas (normalizado)",
        "No asignados (SAE)",
        "Reparto no está en SAE",
        "Cobertura SAE (%)"
    ],
    "Valor": [
        len(sae_set),
        len(rep_set),
        len(inter),
        len(no_asignados),
        len(rep_no_en_sae),
        round((len(inter)/len(sae_set)*100 if len(sae_set) else 0), 2)
    ]
})
display(resumen_df)

                               Metrica    Valor
0                  Personas únicas SAE  1307.00
1          Contratistas únicos Reparto   358.00
2  Coincidencias exactas (normalizado)   249.00
3                   No asignados (SAE)  1058.00
4               Reparto no está en SAE   109.00
5                    Cobertura SAE (%)    19.05

In [ ]:
leeme = pd.DataFrame([
    ("Objetivo", "Asignar a cada responsable del SAE el grupo (columnas E/F/G de Reparto) y auditar inconsistencias."),
    ("Cómo se limpiaron archivos", "Se detectó la fila real de encabezados y se eliminaron filas título. Se removieron columnas Unnamed y filas/columnas vacías."),
    ("Cómo se cruzó", "Se normalizaron nombres (MAYÚSCULAS, sin tildes, sin dobles espacios) y se hizo un cruce SAE <- Reparto."),
    ("RELACION", "Una fila por persona del SAE: muestra si quedó ASIGNADO, sus columnas E/F/G (grupo) y alerta de duplicados."),
    ("NO_ASIGNADOS_SAE", "Responsables SAE que no encontraron coincidencia exacta en Reparto."),
    ("SUGERENCIAS", "Posibles candidatos parecidos en Reparto para revisión manual (NO asigna automáticamente)."),
    ("REPARTO_NO_EN_SAE", "Contratistas en Reparto que no aparecen en SAE (posible digitación/manipulación)."),
    ("DUPLICADOS_REPARTO", "Llaves repetidas en Reparto; pueden generar inconsistencias o duplicar cruces."),
    ("Nota E/F/G", f"E/F/G se tomaron por posición en Reparto (E={col_E}, F={col_F}, G={col_G})."),
    ("Fecha generación", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
], columns=["Sección", "Descripción"])

with pd.ExcelWriter(out_xlsx, engine="openpyxl") as writer:
    leeme.to_excel(writer, index=False, sheet_name="LEEME")
    resumen_df.to_excel(writer, index=False, sheet_name="RESUMEN")
    relacion.to_excel(writer, index=False, sheet_name="RELACION")
    no_asignados.to_excel(writer, index=False, sheet_name="NO_ASIGNADOS_SAE")
    sugerencias.to_excel(writer, index=False, sheet_name="SUGERENCIAS")
    rep_no_en_sae.to_excel(writer, index=False, sheet_name="REPARTO_NO_EN_SAE")
    dups_rep.to_excel(writer, index=False, sheet_name="DUPLICADOS_REPARTO")

print("✅ Excel generado:", out_xlsx)d

✅ Excel generado: output\analisis_grupos_por_persona.xlsx